name: welzijnai
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  flutter_dotenv: ^5.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutterfire_cli: ^1.0.0

  flutter_gen: any
  cloud_firestore: ^4.17.0
  intl: 0.19.0
  shared_preferences: ^2.2.3
  flutter_settings_screens: ^0.3.3-null-safety+2
  provider: ^6.1.2
  fl_chart: ^0.68.0
  just_audio: ^0.9.38
  http: ^0.13.6
  speech_to_text: ^6.6.1
  logger: ^2.3.0
  mockito: ^5.4.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.11.0
  

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - .env
